{
 "title": "CoinInfo",
 "description": "My Data from Luno Crypto Currency",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Luno Course for 1 Bitcoin",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ci_xbteur_bid / 1000", "legendFormat": "BTC Exchange Rate" }
   ]
  },
  {
   "title": "BTC Wallet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_balance{asset=\"XBT\",field=\"balance\"}",
     "legendFormat": "BTC in Wallet"
    }
   ]
  },
  {
   "title": "BTC Wallet in EUR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 1000 - (sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 100000 * 0.5 )",
     "legendFormat": "Euro"
    }
   ]
  },
  {
   "title": "EUR Total",
   "type": "stat",
   "description": "Amount of EUR from both EUR and XBT Wallet",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ci_balance{asset=\"EUR\",field=\"balance\"} / 1000) + (sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 1000 - (sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 100000 * 0.5 ) / 1) + \nsum(ci_balance{asset=\"EUR\",field=\"balance\"} / 1000) + (sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) / 1000 - (sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) / 100000 * 0.5 ) / 1)",
     "legendFormat": "Total EUR in Wallet"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ci_xbteur_bid / 1000", "legendFormat": "BTC Exchange Rate" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "ci_balance{asset=\"XBT\",field=\"balance\"}",
     "legendFormat": "XBT in Wallet"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 1000 - (sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 100000 * 0.5 )",
     "legendFormat": "Euro"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "sum(ci_balance{asset=\"EUR\",field=\"balance\"} / 1000) + (sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 1000 - (sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 100000 * 0.5 ) / 1)",
     "legendFormat": "EUR Total"
    }
   ]
  },
  {
   "title": "Current Luno Course for 1 Ethereum",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ci_etheur_bid / 1000", "legendFormat": "ETH Exchange Rate" }
   ]
  },
  {
   "title": "ETH Wallet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ci_balance{asset=\"ETH\",field=\"balance\"}",
     "legendFormat": "BTC in Wallet"
    }
   ]
  },
  {
   "title": "ETH Wallet in EUR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) / 1000 - (sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) / 100000 * 0.5 )",
     "legendFormat": "Euro"
    }
   ]
  },
  {
   "title": "Bitcoin Difference 7 Days",
   "type": "stat",
   "description": "Amount of EUR from both EUR and XBT Wallet",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ci_xbteur_bid[30m] offset 7d)"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ci_etheur_bid / 1000", "legendFormat": "ETH Exchange Rate" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "ci_balance{asset=\"ETH\",field=\"balance\"}",
     "legendFormat": "ETH in Wallet"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 1000 - (sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 100000 * 0.5 )",
     "legendFormat": "Euro"
    }
   ]
  },
  {
   "title": "Ethereum Difference 7 Days",
   "type": "stat",
   "description": "Amount of EUR from both EUR and ETH Wallet",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ci_etheur_bid[30m] offset 2d)"
    }
   ]
  },
  {
   "title": "Error Messages",
   "type": "stat",
   "description": "ErrorCodes\n// 0    = No Error\n// 1..X = Simple numberings of erros in wallet processing, one id for each error\n// 401  = No API Key set\n// 403  = No API Secret set\n// 500  = Error on balance API call\n",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ci_error" }
   ]
  },
  { "title": "Current Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "timeseries",
   "description": "Current Luno BTC to Euro course",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "ci_xbteur_bid", "legendFormat": "Bitcoin (Bid)" },
    { "expr": "ci_xbteur_ask", "legendFormat": "Bitcoin (Ask)" },
    { "expr": "ci_bitaps_last", "legendFormat": "BitAps" },
    { "expr": "ci_coindesk_last", "legendFormat": "CoinDesk" },
    { "expr": "ci_blockchain_last", "legendFormat": "Blockchain" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) - \n(sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 100 * 0.5 )",
     "legendFormat": "BTC in EUR"
    },
    {
     "expr": "sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) - \n(sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 100 * 0.5 ) - \n(sum(ci_xbteur_bid) * sum(ci_balance{asset=\"XBT\",field=\"balance\"}) / 100 * 1.0 )",
     "legendFormat": "BTC in EUR (- 1,5% Fee)"
    },
    {
     "expr": "ci_balance{asset=\"EUR\",field=\"balance\"}",
     "legendFormat": "{{asset}} Wallet"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Current Luno BTC to Euro course",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    { "expr": "ci_etheur_bid", "legendFormat": "Ethereum (Bid)" },
    { "expr": "ci_etheur_ask", "legendFormat": "Ethereum (Ask)" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    {
     "expr": "sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) - \n(sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) / 100 * 0.5 )",
     "legendFormat": "ETH in EUR"
    },
    {
     "expr": "sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) - \n(sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) / 100 * 0.5 ) - \n(sum(ci_etheur_bid) * sum(ci_balance{asset=\"ETH\",field=\"balance\"}) / 100 * 1.0 )",
     "legendFormat": "ETH in EUR (- 1,5% Fee)"
    },
    {
     "expr": "ci_balance{asset=\"EUR\",field=\"balance\"}",
     "legendFormat": "{{asset}} Wallet"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(ci_xbteur_bid[15m])", "legendFormat": "Changerate of BTC course" },
    { "expr": "rate(ci_etheur_bid[15m])", "legendFormat": "Changerate of ETH course" }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ci_xbteur_last_trade / 1000", "legendFormat": "BTC Last Trades" },
    { "expr": "ci_xbteur_rolling_24", "legendFormat": "BTC Rolling 24h Volume" },
    { "expr": "ci_etheur_rolling_24", "legendFormat": "ETH Rolling 24h Volume" },
    { "expr": "ci_etheur_last_trade / 1000", "legendFormat": "EHT Last Trades" }
   ]
  },
  { "title": "Best Buy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Best Buy Ethereum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(sum(ci_balance{asset=\"EUR\",field=\"balance\"}) / sum(ci_etheur_bid{job=\"coininfo\"}))",
     "legendFormat": "EUR in ETH Balance"
    }
   ]
  },
  {
   "title": "Best Sell Ethereum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(sum(ci_balance{asset=\"ETH\",field=\"balance\"}) * sum(ci_etheur_bid{job=\"coininfo\"} ))",
     "legendFormat": "EUR in ETH Balance"
    }
   ]
  },
  {
   "title": "Best Buy Bitcoin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(sum(ci_balance{asset=\"EUR\",field=\"balance\"}) / sum(ci_xbteur_bid{job=\"coininfo\"}))",
     "legendFormat": "EUR in XBT Balance"
    }
   ]
  },
  {
   "title": "Best Sell Bitcoin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum(sum(ci_balance{asset=\"XBT\",field=\"balance\"}) * sum(ci_xbteur_bid{job=\"coininfo\"} ))",
     "legendFormat": "EUR in XBT Balance"
    }
   ]
  },
  { "title": "Wallets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "All Wallets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "ci_balance{field=\"balance\"}",
     "legendFormat": "{{asset}}"
    }
   ]
  }
 ]
}